name: Sync upstream

on:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:

jobs:

  sync:
    runs-on: ubuntu-latest

    # 添加并发控制
    concurrency:
      group: sync-or-merge
      cancel-in-progress: true

    steps:
      - uses: actions/checkout@v2
        with:
          ref: dev

      - name: Sync upstream dev branch
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@github.com'
          git remote add upstream https://github.com/stashapp/stash.git
          git fetch upstream
          git checkout dev
          git merge --no-edit upstream/develop
          git push origin dev
