name: Sync upstream

on:
  schedule:
    - cron: '0 */6 * * *'
  workflow_dispatch:

jobs:

  sync:
    runs-on: ubuntu-latest

    # 添加并发控制
    concurrency:
      group: sync-or-merge
      cancel-in-progress: true

    steps:
      - uses: actions/checkout@v2
        with:
          ref: dev

      - name: Sync upstream dev branch
        run: |
          git fetch upstream
          git checkout dev
          git merge upstream/develop
          git push origin dev